openapi: 3.0.0
info:
  description: >-
    Service interface for Robot PI controller. Used for establishing a connection to the Robot PI server.
  title: Robot PI Server
  version: 1.0.0
servers:
  - url: http://robotpi.local
    description: Local Robot PI Server
paths:
  /connect:
    get:
      description:  >-
        Connect to the Robot PI server and establish a client connection. Only one client connection at a time is permitted. Client will automatically be disconnected if the connection is lost in excess of the timeout period defined in the server configuration.
      summary: >-
        Connect to the Robot PI server.
      responses:
        200:
          description: >-
            Success response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectSuccessResponse'
        500:
          description: >-
            Unsuccessful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectErrorResponse'
  /disconnect:
    post:
      description: >-
        Halt all streams and close the connection with the server.
      summary: >-
        Disconnect from the server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisconnectRequest'
      responses:
        200:
          description: >-
            Success response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisconnectResponse'
components:
  schemas:
    ConnectSuccessResponse:
      type: object
      properties:
        message:
          type: string
    ConnectErrorResponse:
      type: object
      properties:
        message:
          type: string
        errorCode:
          type: integer
    DisconnectRequest:
      type: object
      properties:
        shutdown:
          type: boolean
          default: false
          description: >-
            Tell the Raspberry PI server to disconnect and shutdown. The server will require a full system start to resume.
    DisconnectResponse:
      type: object
      properties:
        message:
          type: string
    ConfigurationModel:
      type: object
      description: >-
        Server configuration file model. A file 'config.json' MUST reside in the same folder as the service jar. This config will be read to define the configuration to use for the service. The service WILL NOT start without this configuration being provided and complete.
      required:
        - serverPort
        - serverBackLogging
      properties:
        serverIpAddress:
          description: This is the server's IP address that the server will be registered to. Generally this will be null so as not to deviate from the IP address of the system the server is running on.
          type: string
          pattern: ^([0-9]{1,3}\.){3}([0-9]{1,3})$
          example: "localhost"
          readOnly: true
          nullable: true
        serverPort:
          description: This is the port the server will be listening on.
          type: integer
          format: int32
          default: 8001
          example: 8001
          readOnly: true
          nullable: false
        serverBackLogging:
          description: >-
            This represents the maximum number of incoming TCP connections
            which the system will queue internally. Connections are queued while they are waiting to
            be accepted by the HttpServer. When the limit is reached, further connections may be
            rejected (or possibly ignored) by the underlying TCP implementation.
          type: integer
          format: int32
          default: 0
          example: 0
          readOnly: true
          nullable: false